

const Types ={
    NOTIFICATIONSLOADED : "NOTIFICATIONSLOADED",
    ADDNOTIFICATION : "ADDNOTIFICATION",
    UPDATENOTIFICATIONS: "UPDATENOTIFICATIONS",
    READNOTIFICATION : "READNOTIFICATION"
}

export default Types;